version: '3.8'

services:
  # Service MySQL
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password     # Remplacez par votre mot de passe root
      MYSQL_DATABASE: Vivo       # Remplacez par le nom de votre base de données
      MYSQL_USER: admin                # Remplacez par le nom de votre utilisateur
      MYSQL_PASSWORD: password_admin # Remplacez par le mot de passe de l'utilisateur
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql_network

  # Service phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password      # Utilisez le même mot de passe root que ci-dessus
    ports:
      - "8080:80"
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:
